version: "3.7"

volumes:
  bundler_gems:
  node_modules:

services:
  backend: &backend_app
    stdin_open: true
    tty: true
    command: bash -c 'rails s -p 3001'
    ports:
      - ${RAILS_PORT:-3001}:3001
    environment:
      RAILS_ENV: development
    build:
      context: .
      target: "development"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    depends_on:
      - background_service

  background_service:
    <<: *backend_app
    ports: []
    command: bash -c 'bundle exec whenever --update-crontab && sleep infinity'
    depends_on: []

  frontend:
    <<: *backend_app
    environment:
      PORT: 3000
      RAILS_PORT: ${RAILS_PORT:-3001}
    ports:
      - ${PORT:-3000}:3000
    command: bash -c 'cd frontend/ && yarn react-scripts start'
    volumes:
      - .:/app
      - node_modules:/app/frontend/node_modules
    depends_on:
      - backend

  test:
    <<: *backend_app
    environment:
      RAILS_ENV: test
    command: bash -c 'bundle exec rspec && rubocop && cd frontend/ && yarn lint'